### ISSUE TITLE
Help command, remove Thor references

### ISSUE THREAD

**Issue by deepakjois** [deepakjois/dhun#2]
This refers to achiu's fork http://github.com/achiu/dhun

Here is the help output from Thor when the user types `dhun -h`

```
Tasks:
  thor dhun:runner:enqueue SEARCH  #     enqueue songs that match the SEARCH. run dhun help query for filter details.
    once querying is complete, designate the index of song...
  thor dhun:runner:help [TASK]     # Describe available tasks or one specific task
  thor dhun:runner:history         # shows the previously played songs
...<snip>..    
```

It would be preferable to insulate people from the fact that Dhun uses Thor internally. Hence my preference for help message :

```
Tasks available : help history next pause play prev query resume shuffle start_server status stop stop_server
type dhun help <TASKNAME> for additional help on each task
```

Also, when the user types something like `dhun help play`, it currently displays

```
Usage:
  thor dhun:runner:play SEARCH

Options:
  -ar, [--artist=ARTIST] 
..<snip>..
```

It would be preferable replace `thor dhun:runner:play` with `dhun play`.

I looked at the Thor code and it seems easy enough. The methods [task_help](http://github.com/wycats/thor/blob/master/lib/thor.rb#L148) and [help](http://github.com/wycats/thor/blob/master/lib/thor.rb#L164) need to be overridden and tweaked.

**Comment by achiurizo** [comment]
sounds good, will look into this.

**Comment by achiurizo** [comment]
ok got a fix. please pull from my fork.

**Comment by deepakjois** [comment]
I have committed the fix and also integrated the changes with the master branch. But the help display is a bit ugly due to the extremely long help text for all search related comands, i.e. `query`, `play` and `enqueue`. 

Any way to split the help text into a long text and a short text?

**Comment by deepakjois** [comment]
I have committed a patch with shorter help text and other minor capitalization etc : f437d3753258bec0ddafe0a2d6c866f6e7420562

Better suggestions welcome.

**Comment by achiurizo** [comment]
i've pushed changes for help to include an example usage.
