### ISSUE TITLE
Problem with pre-computing of message string in handler.rb, causing incorrect messages

### ISSUE THREAD

**Issue by deepakjois** [deepakjois/dhun#6]
This refers to achiu's fork at http://github.com/achiu/dhun

`handler.rb` has a method called `perform_action`

```
def perform_action(action, arg=nil, message={})
  result = arg.nil? ? @player.send(action) : @player.send(action,arg)
  return [:error,message[:error]].flatten unless result
  return [:success,message[:success]].flatten
end
```

The problem with this method is that the message is taken as an argument even _before_ the action is completed. This causes incorrect messages for actions like `dhun next` and `dhun prev` because the `@player.current` changes after the action is performed, but the message has the old value.

**Comment by achiurizo** [comment]
i notice this issue as well. ill have a fix pushed to my fork

**Comment by achiurizo** [comment]
fix has been committed
