### ISSUE TITLE
Discussion : Play and Enqueue seem to be doing the same thing

### ISSUE THREAD

**Issue by deepakjois** [deepakjois/dhun#7]
This refers to achiu's fork of Dhun http://github.com/achiu/dhun

Initially, 
- `play` was intended to stop whatever was currently playing, empty the queue and start playing the first item in the new set of results.
- `enqueue` was supposed to just add the results to the queue.

This behavior seems to have changed in the fork, and play and enqueue are effectively doing the same thing. We need to either :
- Reinstate the original behavior of `play`, OR
- Remove the `enqueue` command altogether.

Please discuss..

**Comment by achiurizo** [comment]
the intent was to provide some syntatic sugar for the player. However i would agree that the results from the query of the play method should in fact clear the queue and reinstate it with the new queries and play from such.

**Comment by achiurizo** [comment]
play method's behavior has been reinstated in my latest commit.
