### ISSUE TITLE
Numbering of songs in listings

### ISSUE THREAD

**Issue by deepakjois** [deepakjois/dhun#8]
0 is not very user friendly, so we should start numbering from 1. Another reason to use indexes starting from 1 is to allow easier switching using `dhun next` and `dhun prev`. If the listing starts from 1, the skip length becomes immediately obvious.

On a related note, history listing could be ordered in reverse chronological order, with the most recently played song having the index 1. This is again, to facilitate easier skipping using `dhun prev`.

**Comment by achiurizo** [comment]
this has been resolved in my fork
